name: Bug report
description: Report a problem, error, or unexpected behaviour.
body:
  - type: textarea
    attributes:
      label: Bug ID
      description: An incrementing integer.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Title
      description: Short title for the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reporter
      description: The name of the reporter.
  - type: textarea
    attributes:
      label: Date
      description: The date the bug was discovered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: A summary regarding the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device and browser
      description: The type of device and browser the bug was discovered using.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Module
      description: The module of the application that the bug concerns.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Numbered list of steps to reproduce the bug.
      placeholder: |
        1. 
        2. 
        3.
        etc. 
    validations:
      required: true    
  - type: textarea
    attributes:
      label: Expected result
      description: What should happen if the application worked correctly in the situation?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual result
      description: What occurred as a result of the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A more detailed description of the bug.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Frequency
      description: How often is the feature used?
      options:
        - Very frequently
        - Frequently
        - Occasionally
        - Rarely
        - Hardly ever
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Criticality
      description: How critical is the bug?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Priority to fix the bug based on Frequency x Criticality.
      options:
        - Must have
        - Should have
        - Could have
        - Won't have
    validations:
      required: true
  - type: input
    attributes:
      label: Assigned to
      description: Who is the fixing assigned to? Leave empty if no one.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Defect life cycle
      description: Current status of the bug in its life cycle.
      options:
        - Open
        - Assigned
        - Fixed
        - Closed
        - Reopened
        - Rejected / Not a bug
    validations:
      required: true

